name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Amazon Corretto JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean project
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew build -Pandroid.injected.testOnly=false --warning-mode=none
