   name: SonarCloud

  on:
    pull_request:
      branches: ["master"]

  jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
            cache: gradle
        - name: Cache SonarCloud packages
          uses: actions/cache@v4
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: SonarCloud Scan
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: ./gradlew sonar --warning-mode=all